services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_container
    depends_on:
      - postgres
    ports:
      - "3333:3333" # Ajuste conforme a porta exposta no Dockerfile
    env_file:
      - .env

volumes:
  postgres_data:
